/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_ATpackage = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_ATversion = 5,
  anon_sym_ATrequire = 6,
  anon_sym_ATexport = 7,
  anon_sym_DOT = 8,
  anon_sym_STAR = 9,
  sym_identifier = 10,
  sym__number_decimal = 11,
  sym__number_hexadecimal = 12,
  sym__number_binary = 13,
  anon_sym_true = 14,
  anon_sym_false = 15,
  anon_sym_DQUOTE = 16,
  aux_sym_string_content_token1 = 17,
  anon_sym_BSLASH_BSLASH = 18,
  anon_sym_BSLASH_DQUOTE = 19,
  anon_sym_BSLASHt = 20,
  anon_sym_BSLASHr = 21,
  anon_sym_BSLASHs = 22,
  anon_sym_BSLASHf = 23,
  anon_sym_BSLASHv = 24,
  anon_sym_BSLASHn = 25,
  anon_sym_BSLASH_LBRACE = 26,
  anon_sym_RBRACE = 27,
  sym_comment = 28,
  anon_sym_SEMI = 29,
  anon_sym_LF = 30,
  sym_source_file = 31,
  sym__declaration = 32,
  sym__decl_inner = 33,
  sym_const_declaration = 34,
  sym__builtin_declaration = 35,
  sym__expression = 36,
  sym_package_builtin = 37,
  sym_version_builtin = 38,
  sym_require_builtin = 39,
  sym_export_builtin = 40,
  sym_argument_list = 41,
  sym_argument = 42,
  sym_member_access = 43,
  sym_number = 44,
  sym_boolean = 45,
  sym_string = 46,
  sym_escape_char = 47,
  sym_string_template_expr = 48,
  sym__separator = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym__declaration_repeat1 = 51,
  aux_sym_argument_list_repeat1 = 52,
  aux_sym_member_access_repeat1 = 53,
  aux_sym_string_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_ATpackage] = "@package",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_ATversion] = "@version",
  [anon_sym_ATrequire] = "@require",
  [anon_sym_ATexport] = "@export",
  [anon_sym_DOT] = ".",
  [anon_sym_STAR] = "*",
  [sym_identifier] = "identifier",
  [sym__number_decimal] = "_number_decimal",
  [sym__number_hexadecimal] = "_number_hexadecimal",
  [sym__number_binary] = "_number_binary",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_content_token1] = "string_content_token1",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASHt] = "\\t",
  [anon_sym_BSLASHr] = "\\r",
  [anon_sym_BSLASHs] = "\\s",
  [anon_sym_BSLASHf] = "\\f",
  [anon_sym_BSLASHv] = "\\v",
  [anon_sym_BSLASHn] = "\\n",
  [anon_sym_BSLASH_LBRACE] = "\\{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [anon_sym_SEMI] = ";",
  [anon_sym_LF] = "\n",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym__decl_inner] = "_decl_inner",
  [sym_const_declaration] = "const_declaration",
  [sym__builtin_declaration] = "_builtin_declaration",
  [sym__expression] = "_expression",
  [sym_package_builtin] = "package_builtin",
  [sym_version_builtin] = "version_builtin",
  [sym_require_builtin] = "require_builtin",
  [sym_export_builtin] = "export_builtin",
  [sym_argument_list] = "argument_list",
  [sym_argument] = "argument",
  [sym_member_access] = "member_access",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_escape_char] = "escape_char",
  [sym_string_template_expr] = "string_template_expr",
  [sym__separator] = "_separator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__declaration_repeat1] = "_declaration_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_member_access_repeat1] = "member_access_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_ATpackage] = anon_sym_ATpackage,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_ATversion] = anon_sym_ATversion,
  [anon_sym_ATrequire] = anon_sym_ATrequire,
  [anon_sym_ATexport] = anon_sym_ATexport,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_identifier] = sym_identifier,
  [sym__number_decimal] = sym__number_decimal,
  [sym__number_hexadecimal] = sym__number_hexadecimal,
  [sym__number_binary] = sym__number_binary,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_content_token1] = aux_sym_string_content_token1,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASHt] = anon_sym_BSLASHt,
  [anon_sym_BSLASHr] = anon_sym_BSLASHr,
  [anon_sym_BSLASHs] = anon_sym_BSLASHs,
  [anon_sym_BSLASHf] = anon_sym_BSLASHf,
  [anon_sym_BSLASHv] = anon_sym_BSLASHv,
  [anon_sym_BSLASHn] = anon_sym_BSLASHn,
  [anon_sym_BSLASH_LBRACE] = anon_sym_BSLASH_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LF] = anon_sym_LF,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym__decl_inner] = sym__decl_inner,
  [sym_const_declaration] = sym_const_declaration,
  [sym__builtin_declaration] = sym__builtin_declaration,
  [sym__expression] = sym__expression,
  [sym_package_builtin] = sym_package_builtin,
  [sym_version_builtin] = sym_version_builtin,
  [sym_require_builtin] = sym_require_builtin,
  [sym_export_builtin] = sym_export_builtin,
  [sym_argument_list] = sym_argument_list,
  [sym_argument] = sym_argument,
  [sym_member_access] = sym_member_access,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_escape_char] = sym_escape_char,
  [sym_string_template_expr] = sym_string_template_expr,
  [sym__separator] = sym__separator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__declaration_repeat1] = aux_sym__declaration_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_member_access_repeat1] = aux_sym_member_access_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATpackage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATversion] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATrequire] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATexport] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__number_decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__number_hexadecimal] = {
    .visible = false,
    .named = true,
  },
  [sym__number_binary] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__decl_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__builtin_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_package_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_version_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_require_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_export_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string_template_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_member_access_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 11,
  [15] = 13,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 19,
  [40] = 22,
  [41] = 41,
  [42] = 21,
  [43] = 22,
  [44] = 44,
  [45] = 19,
  [46] = 46,
  [47] = 21,
  [48] = 25,
  [49] = 25,
  [50] = 50,
  [51] = 51,
  [52] = 50,
  [53] = 51,
  [54] = 34,
  [55] = 34,
  [56] = 37,
  [57] = 57,
  [58] = 58,
  [59] = 37,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 33,
  [64] = 35,
  [65] = 36,
  [66] = 38,
  [67] = 67,
  [68] = 62,
  [69] = 67,
  [70] = 29,
  [71] = 32,
  [72] = 31,
  [73] = 30,
  [74] = 67,
  [75] = 62,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 78,
  [83] = 83,
  [84] = 81,
  [85] = 83,
  [86] = 86,
  [87] = 87,
  [88] = 78,
  [89] = 86,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 87,
  [94] = 94,
  [95] = 76,
  [96] = 92,
  [97] = 94,
  [98] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '"', 57,
        '(', 35,
        ')', 36,
        '*', 41,
        '.', 40,
        '/', 3,
        '0', 51,
        ':', 33,
        ';', 83,
        '@', 7,
        '\\', 2,
        'f', 42,
        't', 46,
        '}', 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(57);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 65,
        '\\', 63,
        'f', 72,
        'n', 76,
        'r', 68,
        's', 70,
        't', 66,
        'v', 74,
        '{', 78,
      );
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(82);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(8);
      if (lookahead == 'v') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'g') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'k') ADVANCE(5);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'q') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 27:
      if (lookahead == 'x') ADVANCE(19);
      END_STATE();
    case 28:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(54);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      if (lookahead == '\n') ADVANCE(84);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(83);
      if (lookahead == '@') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '@') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_ATpackage);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_ATversion);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_ATrequire);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_ATexport);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__number_decimal);
      if (lookahead == '.') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__number_decimal);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(28);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__number_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__number_hexadecimal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__number_binary);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      if (lookahead == '\n') ADVANCE(81);
      if (lookahead == '"') ADVANCE(82);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      ADVANCE_MAP(
        '"', 65,
        '\\', 64,
        'f', 73,
        'n', 77,
        'r', 69,
        's', 71,
        't', 67,
        'v', 75,
        '{', 79,
      );
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(59);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_BSLASHt);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_BSLASHt);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_BSLASHr);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_BSLASHr);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_BSLASHs);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_BSLASHs);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_BSLASHf);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_BSLASHf);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_BSLASHv);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_BSLASHv);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BSLASHn);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_BSLASHn);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(62);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(81);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(84);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 31},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 31},
  [10] = {.lex_state = 31},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 31},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 30},
  [22] = {.lex_state = 30},
  [23] = {.lex_state = 30},
  [24] = {.lex_state = 30},
  [25] = {.lex_state = 30},
  [26] = {.lex_state = 30},
  [27] = {.lex_state = 30},
  [28] = {.lex_state = 30},
  [29] = {.lex_state = 30},
  [30] = {.lex_state = 30},
  [31] = {.lex_state = 30},
  [32] = {.lex_state = 30},
  [33] = {.lex_state = 30},
  [34] = {.lex_state = 30},
  [35] = {.lex_state = 30},
  [36] = {.lex_state = 30},
  [37] = {.lex_state = 30},
  [38] = {.lex_state = 30},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 30},
  [42] = {.lex_state = 30},
  [43] = {.lex_state = 30},
  [44] = {.lex_state = 30},
  [45] = {.lex_state = 30},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 30},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 31},
  [51] = {.lex_state = 31},
  [52] = {.lex_state = 31},
  [53] = {.lex_state = 31},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 30},
  [56] = {.lex_state = 30},
  [57] = {.lex_state = 30},
  [58] = {.lex_state = 30},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 31},
  [61] = {.lex_state = 31},
  [62] = {.lex_state = 31},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 31},
  [68] = {.lex_state = 31},
  [69] = {.lex_state = 31},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 31},
  [75] = {.lex_state = 31},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 31},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 31},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 31},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_ATpackage] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_ATversion] = ACTIONS(1),
    [anon_sym_ATrequire] = ACTIONS(1),
    [anon_sym_ATexport] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__number_decimal] = ACTIONS(1),
    [sym__number_hexadecimal] = ACTIONS(1),
    [sym__number_binary] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASHt] = ACTIONS(1),
    [anon_sym_BSLASHr] = ACTIONS(1),
    [anon_sym_BSLASHs] = ACTIONS(1),
    [anon_sym_BSLASHf] = ACTIONS(1),
    [anon_sym_BSLASHv] = ACTIONS(1),
    [anon_sym_BSLASHn] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(80),
    [sym__declaration] = STATE(10),
    [sym__decl_inner] = STATE(23),
    [sym_const_declaration] = STATE(23),
    [sym__builtin_declaration] = STATE(23),
    [sym_package_builtin] = STATE(23),
    [sym_version_builtin] = STATE(23),
    [sym_require_builtin] = STATE(23),
    [sym_export_builtin] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_ATpackage] = ACTIONS(7),
    [anon_sym_ATversion] = ACTIONS(9),
    [anon_sym_ATrequire] = ACTIONS(11),
    [anon_sym_ATexport] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_comment] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_ATpackage,
    ACTIONS(21), 1,
      anon_sym_ATversion,
    ACTIONS(23), 1,
      anon_sym_ATrequire,
    ACTIONS(25), 1,
      anon_sym_ATexport,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym__number_decimal,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 2,
      sym__number_hexadecimal,
      sym__number_binary,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(85), 10,
      sym__builtin_declaration,
      sym__expression,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
      sym_member_access,
      sym_number,
      sym_boolean,
      sym_string,
  [45] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_ATpackage,
    ACTIONS(9), 1,
      anon_sym_ATversion,
    ACTIONS(11), 1,
      anon_sym_ATrequire,
    ACTIONS(13), 1,
      anon_sym_ATexport,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      sym__number_decimal,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 2,
      sym__number_hexadecimal,
      sym__number_binary,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 10,
      sym__builtin_declaration,
      sym__expression,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
      sym_member_access,
      sym_number,
      sym_boolean,
      sym_string,
  [90] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_ATpackage,
    ACTIONS(21), 1,
      anon_sym_ATversion,
    ACTIONS(23), 1,
      anon_sym_ATrequire,
    ACTIONS(25), 1,
      anon_sym_ATexport,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym__number_decimal,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 2,
      sym__number_hexadecimal,
      sym__number_binary,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(81), 10,
      sym__builtin_declaration,
      sym__expression,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
      sym_member_access,
      sym_number,
      sym_boolean,
      sym_string,
  [135] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_ATpackage,
    ACTIONS(21), 1,
      anon_sym_ATversion,
    ACTIONS(23), 1,
      anon_sym_ATrequire,
    ACTIONS(25), 1,
      anon_sym_ATexport,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym__number_decimal,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 2,
      sym__number_hexadecimal,
      sym__number_binary,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(83), 10,
      sym__builtin_declaration,
      sym__expression,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
      sym_member_access,
      sym_number,
      sym_boolean,
      sym_string,
  [180] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_ATpackage,
    ACTIONS(21), 1,
      anon_sym_ATversion,
    ACTIONS(23), 1,
      anon_sym_ATrequire,
    ACTIONS(25), 1,
      anon_sym_ATexport,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym__number_decimal,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 2,
      sym__number_hexadecimal,
      sym__number_binary,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(79), 10,
      sym__builtin_declaration,
      sym__expression,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
      sym_member_access,
      sym_number,
      sym_boolean,
      sym_string,
  [225] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_ATpackage,
    ACTIONS(9), 1,
      anon_sym_ATversion,
    ACTIONS(11), 1,
      anon_sym_ATrequire,
    ACTIONS(13), 1,
      anon_sym_ATexport,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      sym__number_decimal,
    ACTIONS(45), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 2,
      sym__number_hexadecimal,
      sym__number_binary,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(28), 10,
      sym__builtin_declaration,
      sym__expression,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
      sym_member_access,
      sym_number,
      sym_boolean,
      sym_string,
  [270] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_ATpackage,
    ACTIONS(21), 1,
      anon_sym_ATversion,
    ACTIONS(23), 1,
      anon_sym_ATrequire,
    ACTIONS(25), 1,
      anon_sym_ATexport,
    ACTIONS(27), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym__number_decimal,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 2,
      sym__number_hexadecimal,
      sym__number_binary,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(84), 10,
      sym__builtin_declaration,
      sym__expression,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
      sym_member_access,
      sym_number,
      sym_boolean,
      sym_string,
  [315] = 9,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      anon_sym_ATpackage,
    ACTIONS(52), 1,
      anon_sym_ATversion,
    ACTIONS(55), 1,
      anon_sym_ATrequire,
    ACTIONS(58), 1,
      anon_sym_ATexport,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(64), 1,
      sym_comment,
    STATE(9), 2,
      sym__declaration,
      aux_sym_source_file_repeat1,
    STATE(23), 7,
      sym__decl_inner,
      sym_const_declaration,
      sym__builtin_declaration,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
  [350] = 9,
    ACTIONS(7), 1,
      anon_sym_ATpackage,
    ACTIONS(9), 1,
      anon_sym_ATversion,
    ACTIONS(11), 1,
      anon_sym_ATrequire,
    ACTIONS(13), 1,
      anon_sym_ATexport,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 1,
      sym_comment,
    STATE(9), 2,
      sym__declaration,
      aux_sym_source_file_repeat1,
    STATE(23), 7,
      sym__decl_inner,
      sym_const_declaration,
      sym__builtin_declaration,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
  [385] = 6,
    ACTIONS(71), 1,
      anon_sym_DQUOTE,
    ACTIONS(73), 1,
      aux_sym_string_content_token1,
    ACTIONS(77), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(79), 1,
      sym_comment,
    STATE(15), 3,
      sym_escape_char,
      sym_string_template_expr,
      aux_sym_string_repeat1,
    ACTIONS(75), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [413] = 6,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      aux_sym_string_content_token1,
    ACTIONS(89), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(12), 3,
      sym_escape_char,
      sym_string_template_expr,
      aux_sym_string_repeat1,
    ACTIONS(86), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [441] = 6,
    ACTIONS(77), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_DQUOTE,
    ACTIONS(94), 1,
      aux_sym_string_content_token1,
    STATE(12), 3,
      sym_escape_char,
      sym_string_template_expr,
      aux_sym_string_repeat1,
    ACTIONS(75), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [469] = 6,
    ACTIONS(77), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_DQUOTE,
    ACTIONS(98), 1,
      aux_sym_string_content_token1,
    STATE(13), 3,
      sym_escape_char,
      sym_string_template_expr,
      aux_sym_string_repeat1,
    ACTIONS(75), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [497] = 6,
    ACTIONS(77), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(94), 1,
      aux_sym_string_content_token1,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    STATE(12), 3,
      sym_escape_char,
      sym_string_template_expr,
      aux_sym_string_repeat1,
    ACTIONS(75), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [525] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_ATpackage,
    ACTIONS(9), 1,
      anon_sym_ATversion,
    ACTIONS(11), 1,
      anon_sym_ATrequire,
    ACTIONS(13), 1,
      anon_sym_ATexport,
    ACTIONS(15), 1,
      sym_identifier,
    STATE(26), 7,
      sym__decl_inner,
      sym_const_declaration,
      sym__builtin_declaration,
      sym_package_builtin,
      sym_version_builtin,
      sym_require_builtin,
      sym_export_builtin,
  [553] = 2,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(102), 11,
      anon_sym_DQUOTE,
      aux_sym_string_content_token1,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
      anon_sym_BSLASH_LBRACE,
  [570] = 2,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(104), 11,
      anon_sym_DQUOTE,
      aux_sym_string_content_token1,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
      anon_sym_BSLASH_LBRACE,
  [587] = 4,
    ACTIONS(110), 1,
      anon_sym_DOT,
    STATE(21), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(108), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [607] = 6,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(118), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym__separator,
    STATE(24), 1,
      aux_sym__declaration_repeat1,
    ACTIONS(114), 6,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
  [631] = 4,
    ACTIONS(124), 1,
      anon_sym_DOT,
    STATE(22), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(122), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [651] = 4,
    ACTIONS(130), 1,
      anon_sym_DOT,
    STATE(22), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(128), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [671] = 6,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    ACTIONS(118), 1,
      anon_sym_LF,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym__separator,
    STATE(20), 1,
      aux_sym__declaration_repeat1,
    ACTIONS(135), 6,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
  [695] = 6,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      anon_sym_SEMI,
    ACTIONS(144), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym__separator,
    STATE(24), 1,
      aux_sym__declaration_repeat1,
    ACTIONS(139), 6,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
  [719] = 2,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(128), 8,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      anon_sym_DOT,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [734] = 2,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(139), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [748] = 2,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(149), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [762] = 2,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(153), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [776] = 2,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(157), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [790] = 2,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(161), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [804] = 2,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(165), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [818] = 2,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(169), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [832] = 2,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(173), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [846] = 2,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(177), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [860] = 2,
    ACTIONS(179), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(181), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [874] = 2,
    ACTIONS(183), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(185), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [888] = 2,
    ACTIONS(187), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(189), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [902] = 2,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(193), 7,
      anon_sym_ATpackage,
      anon_sym_ATversion,
      anon_sym_ATrequire,
      anon_sym_ATexport,
      sym_identifier,
      sym_comment,
      anon_sym_SEMI,
  [916] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_DOT,
    STATE(47), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(106), 3,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [931] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_DOT,
    STATE(40), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(126), 3,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [946] = 6,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(202), 1,
      anon_sym_SEMI,
    ACTIONS(204), 1,
      anon_sym_LF,
    STATE(46), 1,
      aux_sym_argument_list_repeat1,
    STATE(61), 1,
      sym__separator,
  [965] = 5,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(206), 1,
      anon_sym_DOT,
    STATE(43), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(122), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [982] = 5,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LF,
    ACTIONS(208), 1,
      anon_sym_DOT,
    STATE(43), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(128), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [999] = 6,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      anon_sym_LF,
    STATE(44), 1,
      aux_sym_argument_list_repeat1,
    STATE(61), 1,
      sym__separator,
  [1018] = 5,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LF,
    ACTIONS(219), 1,
      anon_sym_DOT,
    STATE(42), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(108), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1035] = 6,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_SEMI,
    ACTIONS(204), 1,
      anon_sym_LF,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_argument_list_repeat1,
    STATE(61), 1,
      sym__separator,
  [1054] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_DOT,
    STATE(40), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(120), 3,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1069] = 3,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LF,
    ACTIONS(128), 3,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_SEMI,
  [1081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 4,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_RBRACE,
  [1091] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(41), 1,
      sym_argument,
    STATE(58), 1,
      sym_member_access,
    STATE(89), 1,
      sym_argument_list,
  [1107] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(41), 1,
      sym_argument,
    STATE(58), 1,
      sym_member_access,
    STATE(93), 1,
      sym_argument_list,
  [1123] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(41), 1,
      sym_argument,
    STATE(58), 1,
      sym_member_access,
    STATE(86), 1,
      sym_argument_list,
  [1139] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(41), 1,
      sym_argument,
    STATE(58), 1,
      sym_member_access,
    STATE(87), 1,
      sym_argument_list,
  [1155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 3,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1164] = 3,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LF,
    ACTIONS(177), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1175] = 3,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LF,
    ACTIONS(189), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1186] = 3,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_LF,
    ACTIONS(211), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1197] = 3,
    ACTIONS(79), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LF,
    ACTIONS(229), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 3,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1217] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_COLON,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(91), 1,
      sym_member_access,
  [1230] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_identifier,
    STATE(57), 1,
      sym_argument,
    STATE(58), 1,
      sym_member_access,
  [1243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_STAR,
    ACTIONS(239), 1,
      sym_identifier,
  [1253] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1285] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
    ACTIONS(241), 1,
      anon_sym_STAR,
  [1295] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_STAR,
    ACTIONS(245), 1,
      sym_identifier,
  [1305] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_identifier,
    ACTIONS(247), 1,
      anon_sym_STAR,
  [1315] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1331] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1339] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_STAR,
    ACTIONS(251), 1,
      sym_identifier,
  [1357] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(253), 1,
      anon_sym_STAR,
  [1367] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_LPAREN,
  [1374] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_COLON,
  [1381] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
  [1388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
  [1395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
  [1409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
  [1416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
  [1423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
  [1430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
  [1437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
  [1444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
  [1451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_identifier,
  [1458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
  [1465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
  [1472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_COLON,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_LPAREN,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
  [1493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LPAREN,
  [1507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_LPAREN,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_LPAREN,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 225,
  [SMALL_STATE(8)] = 270,
  [SMALL_STATE(9)] = 315,
  [SMALL_STATE(10)] = 350,
  [SMALL_STATE(11)] = 385,
  [SMALL_STATE(12)] = 413,
  [SMALL_STATE(13)] = 441,
  [SMALL_STATE(14)] = 469,
  [SMALL_STATE(15)] = 497,
  [SMALL_STATE(16)] = 525,
  [SMALL_STATE(17)] = 553,
  [SMALL_STATE(18)] = 570,
  [SMALL_STATE(19)] = 587,
  [SMALL_STATE(20)] = 607,
  [SMALL_STATE(21)] = 631,
  [SMALL_STATE(22)] = 651,
  [SMALL_STATE(23)] = 671,
  [SMALL_STATE(24)] = 695,
  [SMALL_STATE(25)] = 719,
  [SMALL_STATE(26)] = 734,
  [SMALL_STATE(27)] = 748,
  [SMALL_STATE(28)] = 762,
  [SMALL_STATE(29)] = 776,
  [SMALL_STATE(30)] = 790,
  [SMALL_STATE(31)] = 804,
  [SMALL_STATE(32)] = 818,
  [SMALL_STATE(33)] = 832,
  [SMALL_STATE(34)] = 846,
  [SMALL_STATE(35)] = 860,
  [SMALL_STATE(36)] = 874,
  [SMALL_STATE(37)] = 888,
  [SMALL_STATE(38)] = 902,
  [SMALL_STATE(39)] = 916,
  [SMALL_STATE(40)] = 931,
  [SMALL_STATE(41)] = 946,
  [SMALL_STATE(42)] = 965,
  [SMALL_STATE(43)] = 982,
  [SMALL_STATE(44)] = 999,
  [SMALL_STATE(45)] = 1018,
  [SMALL_STATE(46)] = 1035,
  [SMALL_STATE(47)] = 1054,
  [SMALL_STATE(48)] = 1069,
  [SMALL_STATE(49)] = 1081,
  [SMALL_STATE(50)] = 1091,
  [SMALL_STATE(51)] = 1107,
  [SMALL_STATE(52)] = 1123,
  [SMALL_STATE(53)] = 1139,
  [SMALL_STATE(54)] = 1155,
  [SMALL_STATE(55)] = 1164,
  [SMALL_STATE(56)] = 1175,
  [SMALL_STATE(57)] = 1186,
  [SMALL_STATE(58)] = 1197,
  [SMALL_STATE(59)] = 1208,
  [SMALL_STATE(60)] = 1217,
  [SMALL_STATE(61)] = 1230,
  [SMALL_STATE(62)] = 1243,
  [SMALL_STATE(63)] = 1253,
  [SMALL_STATE(64)] = 1261,
  [SMALL_STATE(65)] = 1269,
  [SMALL_STATE(66)] = 1277,
  [SMALL_STATE(67)] = 1285,
  [SMALL_STATE(68)] = 1295,
  [SMALL_STATE(69)] = 1305,
  [SMALL_STATE(70)] = 1315,
  [SMALL_STATE(71)] = 1323,
  [SMALL_STATE(72)] = 1331,
  [SMALL_STATE(73)] = 1339,
  [SMALL_STATE(74)] = 1347,
  [SMALL_STATE(75)] = 1357,
  [SMALL_STATE(76)] = 1367,
  [SMALL_STATE(77)] = 1374,
  [SMALL_STATE(78)] = 1381,
  [SMALL_STATE(79)] = 1388,
  [SMALL_STATE(80)] = 1395,
  [SMALL_STATE(81)] = 1402,
  [SMALL_STATE(82)] = 1409,
  [SMALL_STATE(83)] = 1416,
  [SMALL_STATE(84)] = 1423,
  [SMALL_STATE(85)] = 1430,
  [SMALL_STATE(86)] = 1437,
  [SMALL_STATE(87)] = 1444,
  [SMALL_STATE(88)] = 1451,
  [SMALL_STATE(89)] = 1458,
  [SMALL_STATE(90)] = 1465,
  [SMALL_STATE(91)] = 1472,
  [SMALL_STATE(92)] = 1479,
  [SMALL_STATE(93)] = 1486,
  [SMALL_STATE(94)] = 1493,
  [SMALL_STATE(95)] = 1500,
  [SMALL_STATE(96)] = 1507,
  [SMALL_STATE(97)] = 1514,
  [SMALL_STATE(98)] = 1521,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_char, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_template_expr, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__declaration_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__declaration_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_declaration, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_declaration, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_builtin, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package_builtin, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version_builtin, 4, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version_builtin, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_builtin, 4, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_require_builtin, 4, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 4, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 4, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_export_builtin, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_export_builtin, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [261] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_betmod(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "betmod",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
