/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_true = 2,
  anon_sym_false = 3,
  sym_escape_char = 4,
  sym_identifier_dot = 5,
  anon_sym_DOT = 6,
  anon_sym_DQUOTE = 7,
  aux_sym__string_content_token1 = 8,
  anon_sym_BSLASH_BSLASH = 9,
  aux_sym_string_line_token1 = 10,
  aux_sym__string_line_content_token1 = 11,
  anon_sym_BSLASH_LBRACE = 12,
  anon_sym_RBRACE = 13,
  sym_number = 14,
  sym_keyword = 15,
  sym__separator = 16,
  aux_sym_comment_line_token1 = 17,
  sym_comment_block = 18,
  anon_sym_COLON = 19,
  anon_sym_ATdir = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  sym_source_file = 23,
  sym_bool = 24,
  sym_type = 25,
  sym_expression = 26,
  sym_member_access = 27,
  sym_string = 28,
  sym__string_content = 29,
  sym_string_line_group = 30,
  sym_string_line = 31,
  sym__string_line_content = 32,
  sym_string_template_expr = 33,
  sym_template_expression = 34,
  sym_comment_line = 35,
  sym_const_declaration = 36,
  sym__stmt = 37,
  sym_dir_statement = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_string_repeat1 = 40,
  aux_sym_string_line_group_repeat1 = 41,
  aux_sym_string_line_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_escape_char] = "escape_char",
  [sym_identifier_dot] = "identifier_dot",
  [anon_sym_DOT] = ".",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__string_content_token1] = "_string_content_token1",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [aux_sym_string_line_token1] = "string_line_token1",
  [aux_sym__string_line_content_token1] = "_string_line_content_token1",
  [anon_sym_BSLASH_LBRACE] = "\\{",
  [anon_sym_RBRACE] = "}",
  [sym_number] = "number",
  [sym_keyword] = "keyword",
  [sym__separator] = "_separator",
  [aux_sym_comment_line_token1] = "comment_line_token1",
  [sym_comment_block] = "comment_block",
  [anon_sym_COLON] = ":",
  [anon_sym_ATdir] = "@dir",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym_bool] = "bool",
  [sym_type] = "type",
  [sym_expression] = "expression",
  [sym_member_access] = "member_access",
  [sym_string] = "string",
  [sym__string_content] = "_string_content",
  [sym_string_line_group] = "string_line_group",
  [sym_string_line] = "string_line",
  [sym__string_line_content] = "_string_line_content",
  [sym_string_template_expr] = "string_template_expr",
  [sym_template_expression] = "template_expression",
  [sym_comment_line] = "comment_line",
  [sym_const_declaration] = "const_declaration",
  [sym__stmt] = "_stmt",
  [sym_dir_statement] = "dir_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_line_group_repeat1] = "string_line_group_repeat1",
  [aux_sym_string_line_repeat1] = "string_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_escape_char] = sym_escape_char,
  [sym_identifier_dot] = sym_identifier_dot,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__string_content_token1] = aux_sym__string_content_token1,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [aux_sym_string_line_token1] = aux_sym_string_line_token1,
  [aux_sym__string_line_content_token1] = aux_sym__string_line_content_token1,
  [anon_sym_BSLASH_LBRACE] = anon_sym_BSLASH_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_number] = sym_number,
  [sym_keyword] = sym_keyword,
  [sym__separator] = sym__separator,
  [aux_sym_comment_line_token1] = aux_sym_comment_line_token1,
  [sym_comment_block] = sym_comment_block,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_ATdir] = anon_sym_ATdir,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_bool] = sym_bool,
  [sym_type] = sym_type,
  [sym_expression] = sym_expression,
  [sym_member_access] = sym_member_access,
  [sym_string] = sym_string,
  [sym__string_content] = sym__string_content,
  [sym_string_line_group] = sym_string_line_group,
  [sym_string_line] = sym_string_line,
  [sym__string_line_content] = sym__string_line_content,
  [sym_string_template_expr] = sym_string_template_expr,
  [sym_template_expression] = sym_template_expression,
  [sym_comment_line] = sym_comment_line,
  [sym_const_declaration] = sym_const_declaration,
  [sym__stmt] = sym__stmt,
  [sym_dir_statement] = sym_dir_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_line_group_repeat1] = aux_sym_string_line_group_repeat1,
  [aux_sym_string_line_repeat1] = aux_sym_string_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_dot] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__string_line_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATdir] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string_line_group] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line] = {
    .visible = true,
    .named = true,
  },
  [sym__string_line_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string_template_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_template_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_const_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_dir_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_line_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_close = 1,
  field_member = 2,
  field_name = 3,
  field_object = 4,
  field_open = 5,
  field_type = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_member] = "member",
  [field_name] = "name",
  [field_object] = "object",
  [field_open] = "open",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_member, 2},
    {field_object, 0},
  [2] =
    {field_name, 0},
    {field_value, 3},
  [4] =
    {field_name, 0},
    {field_type, 2},
    {field_value, 4},
  [7] =
    {field_close, 2},
    {field_open, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 4,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 10,
  [14] = 9,
  [15] = 12,
  [16] = 12,
  [17] = 9,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 25,
  [29] = 25,
  [30] = 24,
  [31] = 23,
  [32] = 26,
  [33] = 24,
  [34] = 23,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 24,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 42,
  [44] = 44,
  [45] = 41,
  [46] = 41,
  [47] = 42,
  [48] = 48,
  [49] = 49,
  [50] = 23,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 67,
  [70] = 67,
  [71] = 67,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '\n', 35,
        '"', 27,
        '\'', 10,
        '(', 61,
        ')', 62,
        '.', 26,
        '/', 7,
        '0', 47,
        ':', 59,
        '@', 14,
        '\\', 13,
        '}', 45,
        0, 55,
        ';', 55,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == ')') ADVANCE(63);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 35,
        '/', 38,
        '\\', 13,
        0, 43,
        ';', 43,
        '\t', 42,
        '\r', 42,
        ' ', 42,
      );
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 27,
        '\'', 10,
        ')', 62,
        '.', 20,
        '/', 7,
        '0', 47,
        '\\', 11,
        '}', 45,
        0, 55,
        '\n', 55,
        ';', 55,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        ')', 62,
        '.', 26,
        '/', 7,
        ':', 59,
        '}', 45,
        0, 55,
        '\n', 55,
        ';', 55,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(57);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 11:
      if (lookahead == '\\') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead == '{') ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '"' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          ('r' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(49);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 20:
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 27,
        '\'', 10,
        '(', 61,
        ')', 62,
        '.', 26,
        '/', 7,
        '0', 47,
        ':', 59,
        '@', 14,
        '\\', 12,
        '}', 45,
        0, 55,
        '\n', 55,
        ';', 55,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_escape_char);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier_dot);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(57);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '\n' ||
          lookahead == '"' ||
          lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_line_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(57);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead == ')') ADVANCE(63);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\n' ||
          lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '\n' ||
          lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead == '/') ADVANCE(38);
      if ((!eof && lookahead == 00) ||
          lookahead == ';') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__string_line_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(50);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(18);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == '-') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_keyword);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__separator);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_comment_line_token1);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_comment_line_token1);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_comment_block);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_ATdir);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 't') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment_line] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_escape_char] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [aux_sym_string_line_token1] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym__separator] = ACTIONS(1),
    [aux_sym_comment_line_token1] = ACTIONS(3),
    [sym_comment_block] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_ATdir] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(61),
    [sym_comment_line] = STATE(1),
    [sym_const_declaration] = STATE(52),
    [sym__stmt] = STATE(51),
    [sym_dir_statement] = STATE(52),
    [aux_sym_source_file_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_comment_line_token1] = ACTIONS(3),
    [sym_comment_block] = ACTIONS(5),
    [anon_sym_ATdir] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(2), 1,
      sym_comment_line,
    STATE(39), 1,
      sym_string_line,
    STATE(43), 1,
      aux_sym_string_line_group_repeat1,
    STATE(48), 1,
      sym_member_access,
    STATE(65), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_identifier_dot,
      sym_number,
      sym_keyword,
    STATE(59), 3,
      sym_bool,
      sym_string,
      sym_string_line_group,
  [45] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(3), 1,
      sym_comment_line,
    STATE(39), 1,
      sym_string_line,
    STATE(42), 1,
      aux_sym_string_line_group_repeat1,
    STATE(48), 1,
      sym_member_access,
    STATE(66), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_identifier_dot,
      sym_number,
      sym_keyword,
    STATE(59), 3,
      sym_bool,
      sym_string,
      sym_string_line_group,
  [90] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(4), 1,
      sym_comment_line,
    STATE(39), 1,
      sym_string_line,
    STATE(47), 1,
      aux_sym_string_line_group_repeat1,
    STATE(48), 1,
      sym_member_access,
    STATE(67), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_identifier_dot,
      sym_number,
      sym_keyword,
    STATE(59), 3,
      sym_bool,
      sym_string,
      sym_string_line_group,
  [135] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(5), 1,
      sym_comment_line,
    STATE(39), 1,
      sym_string_line,
    STATE(42), 1,
      aux_sym_string_line_group_repeat1,
    STATE(48), 1,
      sym_member_access,
    STATE(64), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_identifier_dot,
      sym_number,
      sym_keyword,
    STATE(59), 3,
      sym_bool,
      sym_string,
      sym_string_line_group,
  [180] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(6), 1,
      sym_comment_line,
    STATE(39), 1,
      sym_string_line,
    STATE(47), 1,
      aux_sym_string_line_group_repeat1,
    STATE(48), 1,
      sym_member_access,
    STATE(70), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_identifier_dot,
      sym_number,
      sym_keyword,
    STATE(59), 3,
      sym_bool,
      sym_string,
      sym_string_line_group,
  [225] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(7), 1,
      sym_comment_line,
    STATE(39), 1,
      sym_string_line,
    STATE(47), 1,
      aux_sym_string_line_group_repeat1,
    STATE(48), 1,
      sym_member_access,
    STATE(71), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_identifier_dot,
      sym_number,
      sym_keyword,
    STATE(59), 3,
      sym_bool,
      sym_string,
      sym_string_line_group,
  [270] = 13,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(8), 1,
      sym_comment_line,
    STATE(39), 1,
      sym_string_line,
    STATE(47), 1,
      aux_sym_string_line_group_repeat1,
    STATE(48), 1,
      sym_member_access,
    STATE(69), 1,
      sym_expression,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(17), 3,
      sym_identifier_dot,
      sym_number,
      sym_keyword,
    STATE(59), 3,
      sym_bool,
      sym_string,
      sym_string_line_group,
  [315] = 11,
    ACTIONS(31), 1,
      aux_sym_string_line_token1,
    ACTIONS(33), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    STATE(9), 1,
      sym_comment_line,
    STATE(15), 1,
      aux_sym_string_line_repeat1,
    STATE(29), 1,
      sym__string_line_content,
    STATE(32), 1,
      sym_string_template_expr,
    STATE(34), 1,
      sym_template_expression,
    ACTIONS(27), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
    ACTIONS(29), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [351] = 11,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(43), 1,
      aux_sym_string_line_token1,
    ACTIONS(45), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(10), 1,
      sym_comment_line,
    STATE(14), 1,
      aux_sym_string_line_repeat1,
    STATE(23), 1,
      sym_template_expression,
    STATE(27), 1,
      sym_string_template_expr,
    STATE(28), 1,
      sym__string_line_content,
    ACTIONS(39), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
    ACTIONS(41), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RPAREN,
  [387] = 11,
    ACTIONS(33), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(43), 1,
      aux_sym_string_line_token1,
    STATE(9), 1,
      aux_sym_string_line_repeat1,
    STATE(11), 1,
      sym_comment_line,
    STATE(29), 1,
      sym__string_line_content,
    STATE(32), 1,
      sym_string_template_expr,
    STATE(34), 1,
      sym_template_expression,
    ACTIONS(27), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
    ACTIONS(41), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [423] = 10,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(52), 1,
      aux_sym_string_line_token1,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(25), 1,
      sym__string_line_content,
    STATE(26), 1,
      sym_string_template_expr,
    STATE(31), 1,
      sym_template_expression,
    ACTIONS(47), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
    ACTIONS(50), 2,
      anon_sym_BSLASH_BSLASH,
      sym__separator,
    STATE(12), 2,
      sym_comment_line,
      aux_sym_string_line_repeat1,
  [457] = 11,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(43), 1,
      aux_sym_string_line_token1,
    ACTIONS(59), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(13), 1,
      sym_comment_line,
    STATE(17), 1,
      aux_sym_string_line_repeat1,
    STATE(25), 1,
      sym__string_line_content,
    STATE(26), 1,
      sym_string_template_expr,
    STATE(31), 1,
      sym_template_expression,
    ACTIONS(41), 2,
      anon_sym_BSLASH_BSLASH,
      sym__separator,
    ACTIONS(57), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
  [493] = 11,
    ACTIONS(31), 1,
      aux_sym_string_line_token1,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(45), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(14), 1,
      sym_comment_line,
    STATE(16), 1,
      aux_sym_string_line_repeat1,
    STATE(23), 1,
      sym_template_expression,
    STATE(27), 1,
      sym_string_template_expr,
    STATE(28), 1,
      sym__string_line_content,
    ACTIONS(29), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RPAREN,
    ACTIONS(39), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
  [529] = 10,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(52), 1,
      aux_sym_string_line_token1,
    ACTIONS(64), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(29), 1,
      sym__string_line_content,
    STATE(32), 1,
      sym_string_template_expr,
    STATE(34), 1,
      sym_template_expression,
    ACTIONS(50), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
    ACTIONS(61), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
    STATE(15), 2,
      sym_comment_line,
      aux_sym_string_line_repeat1,
  [563] = 10,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(52), 1,
      aux_sym_string_line_token1,
    ACTIONS(70), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(23), 1,
      sym_template_expression,
    STATE(27), 1,
      sym_string_template_expr,
    STATE(28), 1,
      sym__string_line_content,
    ACTIONS(50), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RPAREN,
    ACTIONS(67), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
    STATE(16), 2,
      sym_comment_line,
      aux_sym_string_line_repeat1,
  [597] = 11,
    ACTIONS(31), 1,
      aux_sym_string_line_token1,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(59), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(12), 1,
      aux_sym_string_line_repeat1,
    STATE(17), 1,
      sym_comment_line,
    STATE(25), 1,
      sym__string_line_content,
    STATE(26), 1,
      sym_string_template_expr,
    STATE(31), 1,
      sym_template_expression,
    ACTIONS(29), 2,
      anon_sym_BSLASH_BSLASH,
      sym__separator,
    ACTIONS(57), 2,
      sym_escape_char,
      aux_sym__string_line_content_token1,
  [633] = 11,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(73), 1,
      sym_escape_char,
    ACTIONS(75), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      aux_sym__string_content_token1,
    ACTIONS(79), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(18), 1,
      sym_comment_line,
    STATE(20), 1,
      aux_sym_string_repeat1,
    STATE(36), 1,
      sym_string_template_expr,
    STATE(49), 1,
      sym__string_content,
    STATE(50), 1,
      sym_template_expression,
  [667] = 11,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(73), 1,
      sym_escape_char,
    ACTIONS(77), 1,
      aux_sym__string_content_token1,
    ACTIONS(79), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(81), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      aux_sym_string_repeat1,
    STATE(19), 1,
      sym_comment_line,
    STATE(36), 1,
      sym_string_template_expr,
    STATE(49), 1,
      sym__string_content,
    STATE(50), 1,
      sym_template_expression,
  [701] = 10,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(83), 1,
      sym_escape_char,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      aux_sym__string_content_token1,
    ACTIONS(91), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(36), 1,
      sym_string_template_expr,
    STATE(49), 1,
      sym__string_content,
    STATE(50), 1,
      sym_template_expression,
    STATE(20), 2,
      sym_comment_line,
      aux_sym_string_repeat1,
  [733] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(99), 1,
      anon_sym_ATdir,
    STATE(51), 1,
      sym__stmt,
    STATE(21), 2,
      sym_comment_line,
      aux_sym_source_file_repeat1,
    STATE(52), 2,
      sym_const_declaration,
      sym_dir_statement,
  [760] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_ATdir,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      aux_sym_source_file_repeat1,
    STATE(22), 1,
      sym_comment_line,
    STATE(51), 1,
      sym__stmt,
    STATE(52), 2,
      sym_const_declaration,
      sym_dir_statement,
  [789] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(106), 1,
      aux_sym_string_line_token1,
    STATE(23), 1,
      sym_comment_line,
    ACTIONS(104), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RPAREN,
  [809] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(110), 1,
      aux_sym_string_line_token1,
    STATE(24), 1,
      sym_comment_line,
    ACTIONS(108), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RPAREN,
  [829] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(114), 1,
      aux_sym_string_line_token1,
    STATE(25), 1,
      sym_comment_line,
    ACTIONS(112), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      sym__separator,
  [849] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(118), 1,
      aux_sym_string_line_token1,
    STATE(26), 1,
      sym_comment_line,
    ACTIONS(116), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      sym__separator,
  [869] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(118), 1,
      aux_sym_string_line_token1,
    STATE(27), 1,
      sym_comment_line,
    ACTIONS(116), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RPAREN,
  [889] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(114), 1,
      aux_sym_string_line_token1,
    STATE(28), 1,
      sym_comment_line,
    ACTIONS(112), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RPAREN,
  [909] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(114), 1,
      aux_sym_string_line_token1,
    STATE(29), 1,
      sym_comment_line,
    ACTIONS(112), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RBRACE,
  [929] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(110), 1,
      aux_sym_string_line_token1,
    STATE(30), 1,
      sym_comment_line,
    ACTIONS(108), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RBRACE,
  [949] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(106), 1,
      aux_sym_string_line_token1,
    STATE(31), 1,
      sym_comment_line,
    ACTIONS(104), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      sym__separator,
  [969] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(118), 1,
      aux_sym_string_line_token1,
    STATE(32), 1,
      sym_comment_line,
    ACTIONS(116), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RBRACE,
  [989] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(110), 1,
      aux_sym_string_line_token1,
    STATE(33), 1,
      sym_comment_line,
    ACTIONS(108), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      sym__separator,
  [1009] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(106), 1,
      aux_sym_string_line_token1,
    STATE(34), 1,
      sym_comment_line,
    ACTIONS(104), 5,
      sym_escape_char,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_line_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_RBRACE,
  [1029] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(35), 1,
      sym_comment_line,
    ACTIONS(120), 5,
      anon_sym_DOT,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [1046] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(122), 1,
      sym_escape_char,
    STATE(36), 1,
      sym_comment_line,
    ACTIONS(124), 3,
      anon_sym_DQUOTE,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
  [1064] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(37), 1,
      sym_comment_line,
    ACTIONS(126), 4,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1080] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(110), 1,
      sym_escape_char,
    STATE(38), 1,
      sym_comment_line,
    ACTIONS(108), 3,
      anon_sym_DQUOTE,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
  [1098] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(39), 1,
      sym_comment_line,
    ACTIONS(128), 4,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1114] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(40), 1,
      sym_comment_line,
    ACTIONS(130), 4,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1130] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(132), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(135), 1,
      sym__separator,
    STATE(39), 1,
      sym_string_line,
    STATE(41), 2,
      sym_comment_line,
      aux_sym_string_line_group_repeat1,
  [1150] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(23), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(137), 1,
      sym__separator,
    STATE(39), 1,
      sym_string_line,
    STATE(41), 1,
      aux_sym_string_line_group_repeat1,
    STATE(42), 1,
      sym_comment_line,
  [1172] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_string_line,
    STATE(43), 1,
      sym_comment_line,
    STATE(46), 1,
      aux_sym_string_line_group_repeat1,
  [1194] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(139), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_COLON,
    STATE(44), 1,
      sym_comment_line,
    STATE(60), 1,
      sym_member_access,
    STATE(68), 1,
      sym_type,
  [1216] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(143), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(39), 1,
      sym_string_line,
    STATE(45), 2,
      sym_comment_line,
      aux_sym_string_line_group_repeat1,
  [1236] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    ACTIONS(146), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(39), 1,
      sym_string_line,
    STATE(46), 2,
      sym_comment_line,
      aux_sym_string_line_group_repeat1,
  [1256] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(25), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      sym_string_line,
    STATE(45), 1,
      aux_sym_string_line_group_repeat1,
    STATE(47), 1,
      sym_comment_line,
  [1278] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(149), 1,
      anon_sym_DOT,
    STATE(48), 1,
      sym_comment_line,
    ACTIONS(151), 3,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1296] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(153), 1,
      sym_escape_char,
    STATE(49), 1,
      sym_comment_line,
    ACTIONS(155), 3,
      anon_sym_DQUOTE,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
  [1314] = 5,
    ACTIONS(35), 1,
      aux_sym_comment_line_token1,
    ACTIONS(37), 1,
      sym_comment_block,
    ACTIONS(106), 1,
      sym_escape_char,
    STATE(50), 1,
      sym_comment_line,
    ACTIONS(104), 3,
      anon_sym_DQUOTE,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
  [1332] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(51), 1,
      sym_comment_line,
    ACTIONS(157), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_ATdir,
  [1347] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(52), 1,
      sym_comment_line,
    ACTIONS(159), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_ATdir,
  [1362] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(53), 1,
      sym_comment_line,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_ATdir,
  [1377] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(54), 1,
      sym_comment_line,
    ACTIONS(163), 3,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1392] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(55), 1,
      sym_comment_line,
    ACTIONS(165), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_ATdir,
  [1407] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(56), 1,
      sym_comment_line,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_ATdir,
  [1422] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(57), 1,
      sym_comment_line,
    ACTIONS(169), 3,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1437] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(58), 1,
      sym_comment_line,
    ACTIONS(171), 3,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1452] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    STATE(59), 1,
      sym_comment_line,
    ACTIONS(151), 3,
      anon_sym_RBRACE,
      sym__separator,
      anon_sym_RPAREN,
  [1467] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(149), 1,
      anon_sym_DOT,
    ACTIONS(173), 1,
      anon_sym_COLON,
    STATE(60), 1,
      sym_comment_line,
  [1483] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_comment_line,
  [1496] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(177), 1,
      sym__separator,
    STATE(62), 1,
      sym_comment_line,
  [1509] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(179), 1,
      sym_identifier,
    STATE(63), 1,
      sym_comment_line,
  [1522] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(181), 1,
      sym__separator,
    STATE(64), 1,
      sym_comment_line,
  [1535] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_comment_line,
  [1548] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(185), 1,
      sym__separator,
    STATE(66), 1,
      sym_comment_line,
  [1561] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      sym_comment_line,
  [1574] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(189), 1,
      anon_sym_COLON,
    STATE(68), 1,
      sym_comment_line,
  [1587] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_comment_line,
  [1600] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_comment_line,
  [1613] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      sym_comment_line,
  [1626] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(197), 1,
      anon_sym_COLON,
    STATE(72), 1,
      sym_comment_line,
  [1639] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_line_token1,
    ACTIONS(5), 1,
      sym_comment_block,
    ACTIONS(199), 1,
      anon_sym_LPAREN,
    STATE(73), 1,
      sym_comment_line,
  [1652] = 1,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 225,
  [SMALL_STATE(8)] = 270,
  [SMALL_STATE(9)] = 315,
  [SMALL_STATE(10)] = 351,
  [SMALL_STATE(11)] = 387,
  [SMALL_STATE(12)] = 423,
  [SMALL_STATE(13)] = 457,
  [SMALL_STATE(14)] = 493,
  [SMALL_STATE(15)] = 529,
  [SMALL_STATE(16)] = 563,
  [SMALL_STATE(17)] = 597,
  [SMALL_STATE(18)] = 633,
  [SMALL_STATE(19)] = 667,
  [SMALL_STATE(20)] = 701,
  [SMALL_STATE(21)] = 733,
  [SMALL_STATE(22)] = 760,
  [SMALL_STATE(23)] = 789,
  [SMALL_STATE(24)] = 809,
  [SMALL_STATE(25)] = 829,
  [SMALL_STATE(26)] = 849,
  [SMALL_STATE(27)] = 869,
  [SMALL_STATE(28)] = 889,
  [SMALL_STATE(29)] = 909,
  [SMALL_STATE(30)] = 929,
  [SMALL_STATE(31)] = 949,
  [SMALL_STATE(32)] = 969,
  [SMALL_STATE(33)] = 989,
  [SMALL_STATE(34)] = 1009,
  [SMALL_STATE(35)] = 1029,
  [SMALL_STATE(36)] = 1046,
  [SMALL_STATE(37)] = 1064,
  [SMALL_STATE(38)] = 1080,
  [SMALL_STATE(39)] = 1098,
  [SMALL_STATE(40)] = 1114,
  [SMALL_STATE(41)] = 1130,
  [SMALL_STATE(42)] = 1150,
  [SMALL_STATE(43)] = 1172,
  [SMALL_STATE(44)] = 1194,
  [SMALL_STATE(45)] = 1216,
  [SMALL_STATE(46)] = 1236,
  [SMALL_STATE(47)] = 1256,
  [SMALL_STATE(48)] = 1278,
  [SMALL_STATE(49)] = 1296,
  [SMALL_STATE(50)] = 1314,
  [SMALL_STATE(51)] = 1332,
  [SMALL_STATE(52)] = 1347,
  [SMALL_STATE(53)] = 1362,
  [SMALL_STATE(54)] = 1377,
  [SMALL_STATE(55)] = 1392,
  [SMALL_STATE(56)] = 1407,
  [SMALL_STATE(57)] = 1422,
  [SMALL_STATE(58)] = 1437,
  [SMALL_STATE(59)] = 1452,
  [SMALL_STATE(60)] = 1467,
  [SMALL_STATE(61)] = 1483,
  [SMALL_STATE(62)] = 1496,
  [SMALL_STATE(63)] = 1509,
  [SMALL_STATE(64)] = 1522,
  [SMALL_STATE(65)] = 1535,
  [SMALL_STATE(66)] = 1548,
  [SMALL_STATE(67)] = 1561,
  [SMALL_STATE(68)] = 1574,
  [SMALL_STATE(69)] = 1587,
  [SMALL_STATE(70)] = 1600,
  [SMALL_STATE(71)] = 1613,
  [SMALL_STATE(72)] = 1626,
  [SMALL_STATE(73)] = 1639,
  [SMALL_STATE(74)] = 1652,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_template_expr, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_template_expr, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_expression, 3, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_expression, 3, 0, 4),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_line_repeat1, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_line_repeat1, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_line_content, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_line_content, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string_content, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_content, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line_group, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 5, 0, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dir_statement, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_declaration, 6, 0, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_betwork(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
