/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_ATdir = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_COLON = 5,
  sym_number_decimal = 6,
  sym_number_hexadecimal = 7,
  sym_number_binary = 8,
  anon_sym_DOT = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_BSLASH_BSLASH = 13,
  anon_sym_LF = 14,
  aux_sym__string_content_token1 = 15,
  anon_sym_BSLASH_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_BSLASH_DQUOTE = 18,
  anon_sym_BSLASHt = 19,
  anon_sym_BSLASHr = 20,
  anon_sym_BSLASHs = 21,
  anon_sym_BSLASHf = 22,
  anon_sym_BSLASHv = 23,
  anon_sym_BSLASHn = 24,
  sym_comment = 25,
  anon_sym_SEMI = 26,
  sym_source_file = 27,
  sym__stmt = 28,
  sym_dir_statement = 29,
  sym_var_statement = 30,
  sym__expression = 31,
  sym_number = 32,
  sym_member_access = 33,
  sym_boolean = 34,
  sym_string = 35,
  sym_string_line = 36,
  sym_string_line_group = 37,
  sym__string_content = 38,
  sym_string_template_expr = 39,
  sym_escape_char = 40,
  sym__separator = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_string_repeat1 = 43,
  aux_sym_string_line_group_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_ATdir] = "@dir",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [sym_number_decimal] = "number_decimal",
  [sym_number_hexadecimal] = "number_hexadecimal",
  [sym_number_binary] = "number_binary",
  [anon_sym_DOT] = ".",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_LF] = "\n",
  [aux_sym__string_content_token1] = "_string_content_token1",
  [anon_sym_BSLASH_LBRACE] = "\\{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASHt] = "\\t",
  [anon_sym_BSLASHr] = "\\r",
  [anon_sym_BSLASHs] = "\\s",
  [anon_sym_BSLASHf] = "\\f",
  [anon_sym_BSLASHv] = "\\v",
  [anon_sym_BSLASHn] = "\\n",
  [sym_comment] = "comment",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__stmt] = "_stmt",
  [sym_dir_statement] = "dir_statement",
  [sym_var_statement] = "var_statement",
  [sym__expression] = "_expression",
  [sym_number] = "number",
  [sym_member_access] = "member_access",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_string_line] = "string_line",
  [sym_string_line_group] = "string_line_group",
  [sym__string_content] = "_string_content",
  [sym_string_template_expr] = "string_template_expr",
  [sym_escape_char] = "escape_char",
  [sym__separator] = "_separator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_line_group_repeat1] = "string_line_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_ATdir] = anon_sym_ATdir,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_number_decimal] = sym_number_decimal,
  [sym_number_hexadecimal] = sym_number_hexadecimal,
  [sym_number_binary] = sym_number_binary,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym__string_content_token1] = aux_sym__string_content_token1,
  [anon_sym_BSLASH_LBRACE] = anon_sym_BSLASH_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASHt] = anon_sym_BSLASHt,
  [anon_sym_BSLASHr] = anon_sym_BSLASHr,
  [anon_sym_BSLASHs] = anon_sym_BSLASHs,
  [anon_sym_BSLASHf] = anon_sym_BSLASHf,
  [anon_sym_BSLASHv] = anon_sym_BSLASHv,
  [anon_sym_BSLASHn] = anon_sym_BSLASHn,
  [sym_comment] = sym_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__stmt] = sym__stmt,
  [sym_dir_statement] = sym_dir_statement,
  [sym_var_statement] = sym_var_statement,
  [sym__expression] = sym__expression,
  [sym_number] = sym_number,
  [sym_member_access] = sym_member_access,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_string_line] = sym_string_line,
  [sym_string_line_group] = sym_string_line_group,
  [sym__string_content] = sym__string_content,
  [sym_string_template_expr] = sym_string_template_expr,
  [sym_escape_char] = sym_escape_char,
  [sym__separator] = sym__separator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_line_group_repeat1] = aux_sym_string_line_group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATdir] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_number_decimal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_hexadecimal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_binary] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHn] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_dir_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_var_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line_group] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string_template_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_line_group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_member = 1,
  field_name = 2,
  field_object = 3,
  field_type = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_member] = "member",
  [field_name] = "name",
  [field_object] = "object",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 3},
  [2] =
    {field_member, 2},
    {field_object, 0},
  [4] =
    {field_name, 0},
    {field_type, 2},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 7,
  [14] = 10,
  [15] = 11,
  [16] = 9,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 22,
  [31] = 31,
  [32] = 32,
  [33] = 21,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 29,
  [40] = 40,
  [41] = 27,
  [42] = 26,
  [43] = 43,
  [44] = 28,
  [45] = 36,
  [46] = 46,
  [47] = 35,
  [48] = 37,
  [49] = 38,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 52,
  [58] = 53,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 24,
        '(', 14,
        ')', 15,
        '.', 23,
        '/', 4,
        '0', 19,
        ':', 16,
        ';', 44,
        '@', 6,
        '\\', 3,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 35,
        '\\', 25,
        'f', 39,
        'n', 41,
        'r', 37,
        's', 38,
        't', 36,
        'v', 40,
        '{', 33,
      );
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(43);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(22);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ';') ADVANCE(44);
      if (lookahead == '@') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_ATdir);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number_decimal);
      if (lookahead == '.') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number_decimal);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(9);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(10);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number_hexadecimal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number_binary);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      ADVANCE_MAP(
        '"', 35,
        '\\', 25,
        'f', 39,
        'n', 41,
        'r', 37,
        's', 38,
        't', 36,
        'v', 40,
        '{', 33,
      );
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '/') ADVANCE(43);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(28);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BSLASHt);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BSLASHr);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASHs);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BSLASHf);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BSLASHv);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASHn);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 't') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 11},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_ATdir] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_number_decimal] = ACTIONS(1),
    [sym_number_hexadecimal] = ACTIONS(1),
    [sym_number_binary] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASHt] = ACTIONS(1),
    [anon_sym_BSLASHr] = ACTIONS(1),
    [anon_sym_BSLASHs] = ACTIONS(1),
    [anon_sym_BSLASHf] = ACTIONS(1),
    [anon_sym_BSLASHv] = ACTIONS(1),
    [anon_sym_BSLASHn] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym__stmt] = STATE(24),
    [sym_dir_statement] = STATE(25),
    [sym_var_statement] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_ATdir] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(42), 1,
      sym_member_access,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(51), 5,
      sym__expression,
      sym_number,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [38] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number_decimal,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(26), 1,
      sym_member_access,
    ACTIONS(27), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(31), 5,
      sym__expression,
      sym_number,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [76] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(42), 1,
      sym_member_access,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(52), 5,
      sym__expression,
      sym_number,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [114] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number_decimal,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(26), 1,
      sym_member_access,
    ACTIONS(27), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(34), 5,
      sym__expression,
      sym_number,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [152] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(42), 1,
      sym_member_access,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(57), 5,
      sym__expression,
      sym_number,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [190] = 6,
    ACTIONS(38), 1,
      anon_sym_LF,
    ACTIONS(40), 1,
      aux_sym__string_content_token1,
    ACTIONS(43), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(46), 1,
      sym_comment,
    STATE(7), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(35), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [219] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_LF,
    ACTIONS(52), 1,
      aux_sym__string_content_token1,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(7), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(48), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [248] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_DQUOTE,
    ACTIONS(60), 1,
      aux_sym__string_content_token1,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(13), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(58), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [277] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      aux_sym__string_content_token1,
    STATE(9), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(58), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [306] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(68), 1,
      anon_sym_LF,
    ACTIONS(70), 1,
      aux_sym__string_content_token1,
    STATE(12), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(48), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [335] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(52), 1,
      aux_sym__string_content_token1,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(72), 1,
      anon_sym_LF,
    STATE(7), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(48), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [364] = 6,
    ACTIONS(38), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(77), 1,
      aux_sym__string_content_token1,
    ACTIONS(80), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(13), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(74), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [393] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(83), 1,
      anon_sym_DQUOTE,
    ACTIONS(85), 1,
      aux_sym__string_content_token1,
    STATE(16), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(58), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [422] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LF,
    ACTIONS(89), 1,
      aux_sym__string_content_token1,
    STATE(8), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(48), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [451] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(60), 1,
      aux_sym__string_content_token1,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    STATE(13), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(58), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [480] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(93), 11,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [497] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(95), 11,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [514] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(95), 11,
      anon_sym_BSLASH_BSLASH,
      anon_sym_LF,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [531] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(93), 11,
      anon_sym_BSLASH_BSLASH,
      anon_sym_LF,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [548] = 5,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(22), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    ACTIONS(99), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [568] = 5,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(22), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    ACTIONS(105), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [588] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(115), 1,
      anon_sym_ATdir,
    STATE(23), 2,
      sym__stmt,
      aux_sym_source_file_repeat1,
    STATE(25), 2,
      sym_dir_statement,
      sym_var_statement,
  [609] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_ATdir,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(23), 2,
      sym__stmt,
      aux_sym_source_file_repeat1,
    STATE(25), 2,
      sym_dir_statement,
      sym_var_statement,
  [630] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 1,
      anon_sym_LF,
    ACTIONS(126), 1,
      anon_sym_SEMI,
    STATE(40), 1,
      sym__separator,
    ACTIONS(122), 2,
      anon_sym_ATdir,
      sym_identifier,
  [650] = 4,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_DOT,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(130), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [666] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(134), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(136), 4,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_BSLASH_BSLASH,
      anon_sym_SEMI,
  [680] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(138), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(140), 4,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_BSLASH_BSLASH,
      anon_sym_SEMI,
  [694] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(144), 4,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_SEMI,
  [708] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(103), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
  [723] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(151), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [736] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(155), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [749] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(97), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
  [764] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(159), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [777] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(163), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [790] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(167), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [803] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(171), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [816] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(175), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 4,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_RBRACE,
  [839] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_ATdir,
      sym_identifier,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_RPAREN,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [857] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_DOT,
    ACTIONS(128), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [868] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_COLON,
    STATE(46), 1,
      sym_member_access,
  [881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 3,
      anon_sym_RPAREN,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [898] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_DOT,
    ACTIONS(185), 1,
      anon_sym_COLON,
  [908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_COLON,
  [939] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
  [946] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
  [953] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_DOT,
  [960] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_identifier,
  [967] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym_identifier,
  [974] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
  [988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_DOT,
  [995] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 114,
  [SMALL_STATE(6)] = 152,
  [SMALL_STATE(7)] = 190,
  [SMALL_STATE(8)] = 219,
  [SMALL_STATE(9)] = 248,
  [SMALL_STATE(10)] = 277,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 335,
  [SMALL_STATE(13)] = 364,
  [SMALL_STATE(14)] = 393,
  [SMALL_STATE(15)] = 422,
  [SMALL_STATE(16)] = 451,
  [SMALL_STATE(17)] = 480,
  [SMALL_STATE(18)] = 497,
  [SMALL_STATE(19)] = 514,
  [SMALL_STATE(20)] = 531,
  [SMALL_STATE(21)] = 548,
  [SMALL_STATE(22)] = 568,
  [SMALL_STATE(23)] = 588,
  [SMALL_STATE(24)] = 609,
  [SMALL_STATE(25)] = 630,
  [SMALL_STATE(26)] = 650,
  [SMALL_STATE(27)] = 666,
  [SMALL_STATE(28)] = 680,
  [SMALL_STATE(29)] = 694,
  [SMALL_STATE(30)] = 708,
  [SMALL_STATE(31)] = 723,
  [SMALL_STATE(32)] = 736,
  [SMALL_STATE(33)] = 749,
  [SMALL_STATE(34)] = 764,
  [SMALL_STATE(35)] = 777,
  [SMALL_STATE(36)] = 790,
  [SMALL_STATE(37)] = 803,
  [SMALL_STATE(38)] = 816,
  [SMALL_STATE(39)] = 829,
  [SMALL_STATE(40)] = 839,
  [SMALL_STATE(41)] = 848,
  [SMALL_STATE(42)] = 857,
  [SMALL_STATE(43)] = 868,
  [SMALL_STATE(44)] = 881,
  [SMALL_STATE(45)] = 890,
  [SMALL_STATE(46)] = 898,
  [SMALL_STATE(47)] = 908,
  [SMALL_STATE(48)] = 916,
  [SMALL_STATE(49)] = 924,
  [SMALL_STATE(50)] = 932,
  [SMALL_STATE(51)] = 939,
  [SMALL_STATE(52)] = 946,
  [SMALL_STATE(53)] = 953,
  [SMALL_STATE(54)] = 960,
  [SMALL_STATE(55)] = 967,
  [SMALL_STATE(56)] = 974,
  [SMALL_STATE(57)] = 981,
  [SMALL_STATE(58)] = 988,
  [SMALL_STATE(59)] = 995,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_char, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_template_expr, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line_group, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line_group, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stmt, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, 0, 2),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 3, 0, 2),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_statement, 4, 0, 1),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_statement, 4, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dir_statement, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dir_statement, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_statement, 5, 0, 3),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_statement, 5, 0, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [197] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_betwork(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "betwork",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
