/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_ATdir = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_COLON_COLON = 5,
  sym_number_decimal = 6,
  sym_number_hexadecimal = 7,
  sym_number_binary = 8,
  anon_sym_DOT = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_BSLASH_BSLASH = 13,
  anon_sym_LF = 14,
  aux_sym__string_content_token1 = 15,
  anon_sym_BSLASH_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_BSLASH_DQUOTE = 18,
  anon_sym_BSLASHt = 19,
  anon_sym_BSLASHr = 20,
  anon_sym_BSLASHs = 21,
  anon_sym_BSLASHf = 22,
  anon_sym_BSLASHv = 23,
  anon_sym_BSLASHn = 24,
  sym_comment = 25,
  anon_sym_SEMI = 26,
  sym_source_file = 27,
  sym__stmt = 28,
  sym_dir_statement = 29,
  sym_var_statement = 30,
  sym__expression = 31,
  sym_number = 32,
  sym_member_access = 33,
  sym_boolean = 34,
  sym_string = 35,
  sym_string_line = 36,
  sym_string_line_group = 37,
  sym__string_content = 38,
  sym_string_template_expr = 39,
  sym_escape_char = 40,
  sym__separator = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_member_access_repeat1 = 43,
  aux_sym_string_repeat1 = 44,
  aux_sym_string_line_group_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_ATdir] = "@dir",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON_COLON] = "::",
  [sym_number_decimal] = "number_decimal",
  [sym_number_hexadecimal] = "number_hexadecimal",
  [sym_number_binary] = "number_binary",
  [anon_sym_DOT] = ".",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_LF] = "\n",
  [aux_sym__string_content_token1] = "_string_content_token1",
  [anon_sym_BSLASH_LBRACE] = "\\{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASHt] = "\\t",
  [anon_sym_BSLASHr] = "\\r",
  [anon_sym_BSLASHs] = "\\s",
  [anon_sym_BSLASHf] = "\\f",
  [anon_sym_BSLASHv] = "\\v",
  [anon_sym_BSLASHn] = "\\n",
  [sym_comment] = "comment",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__stmt] = "_stmt",
  [sym_dir_statement] = "dir_statement",
  [sym_var_statement] = "var_statement",
  [sym__expression] = "_expression",
  [sym_number] = "number",
  [sym_member_access] = "member_access",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_string_line] = "string_line",
  [sym_string_line_group] = "string_line_group",
  [sym__string_content] = "_string_content",
  [sym_string_template_expr] = "string_template_expr",
  [sym_escape_char] = "escape_char",
  [sym__separator] = "_separator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_member_access_repeat1] = "member_access_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_line_group_repeat1] = "string_line_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_ATdir] = anon_sym_ATdir,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_number_decimal] = sym_number_decimal,
  [sym_number_hexadecimal] = sym_number_hexadecimal,
  [sym_number_binary] = sym_number_binary,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym__string_content_token1] = aux_sym__string_content_token1,
  [anon_sym_BSLASH_LBRACE] = anon_sym_BSLASH_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASHt] = anon_sym_BSLASHt,
  [anon_sym_BSLASHr] = anon_sym_BSLASHr,
  [anon_sym_BSLASHs] = anon_sym_BSLASHs,
  [anon_sym_BSLASHf] = anon_sym_BSLASHf,
  [anon_sym_BSLASHv] = anon_sym_BSLASHv,
  [anon_sym_BSLASHn] = anon_sym_BSLASHn,
  [sym_comment] = sym_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__stmt] = sym__stmt,
  [sym_dir_statement] = sym_dir_statement,
  [sym_var_statement] = sym_var_statement,
  [sym__expression] = sym__expression,
  [sym_number] = sym_number,
  [sym_member_access] = sym_member_access,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_string_line] = sym_string_line,
  [sym_string_line_group] = sym_string_line_group,
  [sym__string_content] = sym__string_content,
  [sym_string_template_expr] = sym_string_template_expr,
  [sym_escape_char] = sym_escape_char,
  [sym__separator] = sym__separator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_member_access_repeat1] = aux_sym_member_access_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_line_group_repeat1] = aux_sym_string_line_group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATdir] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_number_decimal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_hexadecimal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_binary] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHn] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_dir_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_var_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line_group] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string_template_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_member_access_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_line_group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 8,
  [12] = 10,
  [13] = 7,
  [14] = 6,
  [15] = 9,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 16,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 20,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 21,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 25,
  [40] = 26,
  [41] = 24,
  [42] = 27,
  [43] = 29,
  [44] = 28,
  [45] = 45,
  [46] = 32,
  [47] = 33,
  [48] = 37,
  [49] = 34,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 25,
        '(', 15,
        ')', 16,
        '.', 24,
        '/', 4,
        '0', 20,
        ':', 5,
        ';', 45,
        '@', 7,
        '\\', 3,
        '}', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 36,
        '\\', 26,
        'f', 40,
        'n', 42,
        'r', 38,
        's', 39,
        't', 37,
        'v', 41,
        '{', 34,
      );
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(23);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '.') ADVANCE(24);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ';') ADVANCE(45);
      if (lookahead == '@') ADVANCE(7);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_ATdir);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number_decimal);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number_decimal);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(10);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(11);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number_hexadecimal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number_binary);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      ADVANCE_MAP(
        '"', 36,
        '\\', 26,
        'f', 40,
        'n', 42,
        'r', 38,
        's', 39,
        't', 37,
        'v', 41,
        '{', 34,
      );
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(31);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BSLASHt);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASHr);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BSLASHs);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BSLASHf);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASHv);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASHn);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 't') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_ATdir] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_number_decimal] = ACTIONS(1),
    [sym_number_hexadecimal] = ACTIONS(1),
    [sym_number_binary] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASHt] = ACTIONS(1),
    [anon_sym_BSLASHr] = ACTIONS(1),
    [anon_sym_BSLASHs] = ACTIONS(1),
    [anon_sym_BSLASHf] = ACTIONS(1),
    [anon_sym_BSLASHv] = ACTIONS(1),
    [anon_sym_BSLASHn] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym__stmt] = STATE(22),
    [sym_dir_statement] = STATE(30),
    [sym_var_statement] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_ATdir] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(50), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [36] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(53), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [72] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number_decimal,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(27), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(36), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [108] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(57), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [144] = 6,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(40), 1,
      aux_sym__string_content_token1,
    ACTIONS(43), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(46), 1,
      sym_comment,
    STATE(6), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(37), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [173] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      aux_sym__string_content_token1,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(9), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(50), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [202] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_LF,
    ACTIONS(60), 1,
      aux_sym__string_content_token1,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(14), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(56), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [231] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      aux_sym__string_content_token1,
    STATE(6), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(50), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [260] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(68), 1,
      anon_sym_LF,
    ACTIONS(70), 1,
      aux_sym__string_content_token1,
    STATE(8), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(56), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [289] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(60), 1,
      aux_sym__string_content_token1,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(72), 1,
      anon_sym_LF,
    STATE(14), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(56), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [318] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LF,
    ACTIONS(76), 1,
      aux_sym__string_content_token1,
    STATE(11), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(56), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [347] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    ACTIONS(80), 1,
      aux_sym__string_content_token1,
    STATE(15), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(50), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [376] = 6,
    ACTIONS(35), 1,
      anon_sym_LF,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(85), 1,
      aux_sym__string_content_token1,
    ACTIONS(88), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(14), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(82), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [405] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(66), 1,
      aux_sym__string_content_token1,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    STATE(6), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(50), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [434] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(93), 11,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [451] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(95), 11,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [468] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(95), 11,
      anon_sym_BSLASH_BSLASH,
      anon_sym_LF,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [485] = 2,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(93), 11,
      anon_sym_BSLASH_BSLASH,
      anon_sym_LF,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [502] = 5,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(20), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    ACTIONS(99), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [522] = 5,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(20), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    ACTIONS(106), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [542] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_ATdir,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    STATE(23), 2,
      sym__stmt,
      aux_sym_source_file_repeat1,
    STATE(30), 2,
      sym_dir_statement,
      sym_var_statement,
  [563] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_ATdir,
    STATE(23), 2,
      sym__stmt,
      aux_sym_source_file_repeat1,
    STATE(30), 2,
      sym_dir_statement,
      sym_var_statement,
  [584] = 5,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(122), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [603] = 5,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(128), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [622] = 5,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_DOT,
    STATE(24), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(135), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [641] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(139), 4,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_BSLASH_BSLASH,
      anon_sym_SEMI,
  [655] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(143), 4,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_BSLASH_BSLASH,
      anon_sym_SEMI,
  [669] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(128), 4,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_SEMI,
  [683] = 6,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 1,
      anon_sym_LF,
    ACTIONS(151), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym__separator,
    ACTIONS(147), 2,
      anon_sym_ATdir,
      sym_identifier,
  [703] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(97), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    STATE(31), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
  [718] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(158), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [731] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(162), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [744] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(166), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [757] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(104), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    STATE(31), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
  [772] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(168), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(170), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [785] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(172), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(174), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [798] = 3,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(176), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(178), 3,
      anon_sym_ATdir,
      sym_identifier,
      anon_sym_SEMI,
  [811] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_DOT,
    STATE(39), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(126), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [825] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_DOT,
    STATE(41), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(133), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [839] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_DOT,
    STATE(39), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(120), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [853] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      anon_sym_RPAREN,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 3,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_RBRACE,
  [871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_RPAREN,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      anon_sym_ATdir,
      sym_identifier,
  [889] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [905] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
  [928] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LPAREN,
  [935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_COLON_COLON,
  [942] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
  [949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
  [956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
  [963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      sym_identifier,
  [970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 202,
  [SMALL_STATE(9)] = 231,
  [SMALL_STATE(10)] = 260,
  [SMALL_STATE(11)] = 289,
  [SMALL_STATE(12)] = 318,
  [SMALL_STATE(13)] = 347,
  [SMALL_STATE(14)] = 376,
  [SMALL_STATE(15)] = 405,
  [SMALL_STATE(16)] = 434,
  [SMALL_STATE(17)] = 451,
  [SMALL_STATE(18)] = 468,
  [SMALL_STATE(19)] = 485,
  [SMALL_STATE(20)] = 502,
  [SMALL_STATE(21)] = 522,
  [SMALL_STATE(22)] = 542,
  [SMALL_STATE(23)] = 563,
  [SMALL_STATE(24)] = 584,
  [SMALL_STATE(25)] = 603,
  [SMALL_STATE(26)] = 622,
  [SMALL_STATE(27)] = 641,
  [SMALL_STATE(28)] = 655,
  [SMALL_STATE(29)] = 669,
  [SMALL_STATE(30)] = 683,
  [SMALL_STATE(31)] = 703,
  [SMALL_STATE(32)] = 718,
  [SMALL_STATE(33)] = 731,
  [SMALL_STATE(34)] = 744,
  [SMALL_STATE(35)] = 757,
  [SMALL_STATE(36)] = 772,
  [SMALL_STATE(37)] = 785,
  [SMALL_STATE(38)] = 798,
  [SMALL_STATE(39)] = 811,
  [SMALL_STATE(40)] = 825,
  [SMALL_STATE(41)] = 839,
  [SMALL_STATE(42)] = 853,
  [SMALL_STATE(43)] = 862,
  [SMALL_STATE(44)] = 871,
  [SMALL_STATE(45)] = 880,
  [SMALL_STATE(46)] = 889,
  [SMALL_STATE(47)] = 897,
  [SMALL_STATE(48)] = 905,
  [SMALL_STATE(49)] = 913,
  [SMALL_STATE(50)] = 921,
  [SMALL_STATE(51)] = 928,
  [SMALL_STATE(52)] = 935,
  [SMALL_STATE(53)] = 942,
  [SMALL_STATE(54)] = 949,
  [SMALL_STATE(55)] = 956,
  [SMALL_STATE(56)] = 963,
  [SMALL_STATE(57)] = 970,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_char, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_template_expr, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line_group, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line_group, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stmt, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_statement, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_statement, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dir_statement, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dir_statement, 4, 0, 0),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [195] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_betwork(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "betwork",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
