/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 56
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_dir = 1,
  anon_sym_COLON_COLON = 2,
  sym_identifier = 3,
  sym_number_decimal = 4,
  sym_number_hexadecimal = 5,
  sym_number_binary = 6,
  anon_sym_DOT = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_DQUOTE = 10,
  anon_sym_BSLASH_BSLASH = 11,
  anon_sym_LF = 12,
  aux_sym__string_content_token1 = 13,
  anon_sym_BSLASH_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_BSLASH_DQUOTE = 16,
  anon_sym_BSLASHt = 17,
  anon_sym_BSLASHr = 18,
  anon_sym_BSLASHs = 19,
  anon_sym_BSLASHf = 20,
  anon_sym_BSLASHv = 21,
  anon_sym_BSLASHn = 22,
  sym_comment = 23,
  anon_sym_SEMI = 24,
  sym_source_file = 25,
  sym__stmt = 26,
  sym_dir_statement = 27,
  sym_var_statement = 28,
  sym__expression = 29,
  sym_number = 30,
  sym_member_access = 31,
  sym_boolean = 32,
  sym_string = 33,
  sym_string_line = 34,
  sym_string_line_group = 35,
  sym__string_content = 36,
  sym_string_template_expr = 37,
  sym_escape_char = 38,
  sym__separator = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_member_access_repeat1 = 41,
  aux_sym_string_repeat1 = 42,
  aux_sym_string_line_group_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_dir] = "dir",
  [anon_sym_COLON_COLON] = "::",
  [sym_identifier] = "identifier",
  [sym_number_decimal] = "number_decimal",
  [sym_number_hexadecimal] = "number_hexadecimal",
  [sym_number_binary] = "number_binary",
  [anon_sym_DOT] = ".",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_LF] = "\n",
  [aux_sym__string_content_token1] = "_string_content_token1",
  [anon_sym_BSLASH_LBRACE] = "\\{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASHt] = "\\t",
  [anon_sym_BSLASHr] = "\\r",
  [anon_sym_BSLASHs] = "\\s",
  [anon_sym_BSLASHf] = "\\f",
  [anon_sym_BSLASHv] = "\\v",
  [anon_sym_BSLASHn] = "\\n",
  [sym_comment] = "comment",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__stmt] = "_stmt",
  [sym_dir_statement] = "dir_statement",
  [sym_var_statement] = "var_statement",
  [sym__expression] = "_expression",
  [sym_number] = "number",
  [sym_member_access] = "member_access",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_string_line] = "string_line",
  [sym_string_line_group] = "string_line_group",
  [sym__string_content] = "_string_content",
  [sym_string_template_expr] = "string_template_expr",
  [sym_escape_char] = "escape_char",
  [sym__separator] = "_separator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_member_access_repeat1] = "member_access_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_line_group_repeat1] = "string_line_group_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_dir] = anon_sym_dir,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_identifier] = sym_identifier,
  [sym_number_decimal] = sym_number_decimal,
  [sym_number_hexadecimal] = sym_number_hexadecimal,
  [sym_number_binary] = sym_number_binary,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym__string_content_token1] = aux_sym__string_content_token1,
  [anon_sym_BSLASH_LBRACE] = anon_sym_BSLASH_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASHt] = anon_sym_BSLASHt,
  [anon_sym_BSLASHr] = anon_sym_BSLASHr,
  [anon_sym_BSLASHs] = anon_sym_BSLASHs,
  [anon_sym_BSLASHf] = anon_sym_BSLASHf,
  [anon_sym_BSLASHv] = anon_sym_BSLASHv,
  [anon_sym_BSLASHn] = anon_sym_BSLASHn,
  [sym_comment] = sym_comment,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__stmt] = sym__stmt,
  [sym_dir_statement] = sym_dir_statement,
  [sym_var_statement] = sym_var_statement,
  [sym__expression] = sym__expression,
  [sym_number] = sym_number,
  [sym_member_access] = sym_member_access,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_string_line] = sym_string_line,
  [sym_string_line_group] = sym_string_line_group,
  [sym__string_content] = sym__string_content,
  [sym_string_template_expr] = sym_string_template_expr,
  [sym_escape_char] = sym_escape_char,
  [sym__separator] = sym__separator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_member_access_repeat1] = aux_sym_member_access_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_line_group_repeat1] = aux_sym_string_line_group_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_dir] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number_decimal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_hexadecimal] = {
    .visible = true,
    .named = true,
  },
  [sym_number_binary] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHn] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_dir_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_var_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line_group] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string_template_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_char] = {
    .visible = true,
    .named = true,
  },
  [sym__separator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_member_access_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_line_group_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 7,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 9,
  [15] = 12,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 17,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 20,
  [38] = 21,
  [39] = 39,
  [40] = 22,
  [41] = 26,
  [42] = 25,
  [43] = 28,
  [44] = 30,
  [45] = 27,
  [46] = 46,
  [47] = 47,
  [48] = 46,
  [49] = 49,
  [50] = 50,
  [51] = 34,
  [52] = 32,
  [53] = 35,
  [54] = 49,
  [55] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 34,
        '.', 31,
        '/', 6,
        '0', 27,
        ':', 7,
        ';', 54,
        '\\', 4,
        'd', 19,
        'f', 16,
        't', 21,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 't') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 45,
        '\\', 35,
        'f', 49,
        'n', 51,
        'r', 47,
        's', 48,
        't', 46,
        'v', 50,
        '{', 43,
      );
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == '\\') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(30);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(37);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ';') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == 'd') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'd') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_dir);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number_decimal);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number_decimal);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(9);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(10);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number_hexadecimal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number_binary);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      ADVANCE_MAP(
        '"', 45,
        '\\', 35,
        'f', 49,
        'n', 51,
        'r', 47,
        's', 48,
        't', 46,
        'v', 50,
        '{', 43,
      );
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '/') ADVANCE(53);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__string_content_token1);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(38);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BSLASHt);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BSLASHr);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BSLASHs);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BSLASHf);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BSLASHv);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_BSLASHn);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_dir] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number_decimal] = ACTIONS(1),
    [sym_number_hexadecimal] = ACTIONS(1),
    [sym_number_binary] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASHt] = ACTIONS(1),
    [anon_sym_BSLASHr] = ACTIONS(1),
    [anon_sym_BSLASHs] = ACTIONS(1),
    [anon_sym_BSLASHf] = ACTIONS(1),
    [anon_sym_BSLASHv] = ACTIONS(1),
    [anon_sym_BSLASHn] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(50),
    [sym__stmt] = STATE(23),
    [sym_dir_statement] = STATE(29),
    [sym_var_statement] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_dir] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(33), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [36] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      sym_number_decimal,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(15), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(31), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [72] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number_decimal,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(27), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(37), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(49), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [108] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_number_decimal,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(27), 2,
      sym_number_hexadecimal,
      sym_number_binary,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(37), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    STATE(54), 6,
      sym__expression,
      sym_number,
      sym_member_access,
      sym_boolean,
      sym_string,
      sym_string_line_group,
  [144] = 6,
    ACTIONS(35), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      aux_sym__string_content_token1,
    ACTIONS(41), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(43), 1,
      sym_comment,
    STATE(15), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(37), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [173] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_LF,
    ACTIONS(49), 1,
      aux_sym__string_content_token1,
    ACTIONS(51), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(11), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(45), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [202] = 6,
    ACTIONS(41), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(55), 1,
      aux_sym__string_content_token1,
    STATE(12), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(37), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [231] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(57), 1,
      anon_sym_LF,
    ACTIONS(59), 1,
      aux_sym__string_content_token1,
    STATE(10), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(45), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [260] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(49), 1,
      aux_sym__string_content_token1,
    ACTIONS(51), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(61), 1,
      anon_sym_LF,
    STATE(11), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(45), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [289] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_LF,
    ACTIONS(68), 1,
      aux_sym__string_content_token1,
    ACTIONS(71), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(11), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(63), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [318] = 6,
    ACTIONS(41), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_DQUOTE,
    ACTIONS(76), 1,
      aux_sym__string_content_token1,
    STATE(13), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(37), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [347] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      aux_sym__string_content_token1,
    ACTIONS(84), 1,
      anon_sym_BSLASH_LBRACE,
    STATE(13), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(78), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [376] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(87), 1,
      anon_sym_LF,
    ACTIONS(89), 1,
      aux_sym__string_content_token1,
    STATE(7), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(45), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [405] = 6,
    ACTIONS(41), 1,
      anon_sym_BSLASH_LBRACE,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(76), 1,
      aux_sym__string_content_token1,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    STATE(13), 4,
      sym__string_content,
      sym_string_template_expr,
      sym_escape_char,
      aux_sym_string_repeat1,
    ACTIONS(37), 8,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [434] = 2,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(93), 11,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [451] = 2,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(95), 11,
      anon_sym_DQUOTE,
      anon_sym_BSLASH_BSLASH,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [468] = 2,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(93), 11,
      anon_sym_BSLASH_BSLASH,
      anon_sym_LF,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [485] = 2,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(95), 11,
      anon_sym_BSLASH_BSLASH,
      anon_sym_LF,
      aux_sym__string_content_token1,
      anon_sym_BSLASH_LBRACE,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASHt,
      anon_sym_BSLASHr,
      anon_sym_BSLASHs,
      anon_sym_BSLASHf,
      anon_sym_BSLASHv,
      anon_sym_BSLASHn,
  [502] = 5,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(21), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    ACTIONS(99), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [522] = 5,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    STATE(21), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
    ACTIONS(105), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [542] = 5,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_DOT,
    STATE(26), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(112), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [561] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_dir,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    STATE(24), 2,
      sym__stmt,
      aux_sym_source_file_repeat1,
    STATE(29), 2,
      sym_dir_statement,
      sym_var_statement,
  [582] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      anon_sym_dir,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(24), 2,
      sym__stmt,
      aux_sym_source_file_repeat1,
    STATE(29), 2,
      sym_dir_statement,
      sym_var_statement,
  [603] = 5,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(128), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [622] = 5,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym_member_access_repeat1,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(135), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [641] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(128), 4,
      anon_sym_dir,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_SEMI,
  [655] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(139), 4,
      anon_sym_dir,
      sym_identifier,
      anon_sym_BSLASH_BSLASH,
      anon_sym_SEMI,
  [669] = 6,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 1,
      anon_sym_LF,
    ACTIONS(147), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      sym__separator,
    ACTIONS(143), 2,
      anon_sym_dir,
      sym_identifier,
  [689] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(151), 4,
      anon_sym_dir,
      sym_identifier,
      anon_sym_BSLASH_BSLASH,
      anon_sym_SEMI,
  [703] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(155), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [716] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(159), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [729] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(163), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [742] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(167), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [755] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(171), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [768] = 3,
    ACTIONS(43), 1,
      sym_comment,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(175), 3,
      anon_sym_dir,
      sym_identifier,
      anon_sym_SEMI,
  [781] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_BSLASH_BSLASH,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
  [795] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(177), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(38), 2,
      sym_string_line,
      aux_sym_string_line_group_repeat1,
  [809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 2,
      anon_sym_dir,
      sym_identifier,
  [820] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(184), 1,
      anon_sym_DOT,
    STATE(41), 1,
      aux_sym_member_access_repeat1,
  [833] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(184), 1,
      anon_sym_DOT,
    STATE(42), 1,
      aux_sym_member_access_repeat1,
  [846] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(186), 1,
      anon_sym_DOT,
    STATE(42), 1,
      aux_sym_member_access_repeat1,
  [859] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_BSLASH_BSLASH,
      anon_sym_RBRACE,
  [875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_DOT,
      anon_sym_RBRACE,
  [883] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_identifier,
  [890] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_COLON_COLON,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym_identifier,
  [904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
  [911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [918] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
  [925] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
  [932] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
  [939] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
  [946] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 202,
  [SMALL_STATE(9)] = 231,
  [SMALL_STATE(10)] = 260,
  [SMALL_STATE(11)] = 289,
  [SMALL_STATE(12)] = 318,
  [SMALL_STATE(13)] = 347,
  [SMALL_STATE(14)] = 376,
  [SMALL_STATE(15)] = 405,
  [SMALL_STATE(16)] = 434,
  [SMALL_STATE(17)] = 451,
  [SMALL_STATE(18)] = 468,
  [SMALL_STATE(19)] = 485,
  [SMALL_STATE(20)] = 502,
  [SMALL_STATE(21)] = 522,
  [SMALL_STATE(22)] = 542,
  [SMALL_STATE(23)] = 561,
  [SMALL_STATE(24)] = 582,
  [SMALL_STATE(25)] = 603,
  [SMALL_STATE(26)] = 622,
  [SMALL_STATE(27)] = 641,
  [SMALL_STATE(28)] = 655,
  [SMALL_STATE(29)] = 669,
  [SMALL_STATE(30)] = 689,
  [SMALL_STATE(31)] = 703,
  [SMALL_STATE(32)] = 716,
  [SMALL_STATE(33)] = 729,
  [SMALL_STATE(34)] = 742,
  [SMALL_STATE(35)] = 755,
  [SMALL_STATE(36)] = 768,
  [SMALL_STATE(37)] = 781,
  [SMALL_STATE(38)] = 795,
  [SMALL_STATE(39)] = 809,
  [SMALL_STATE(40)] = 820,
  [SMALL_STATE(41)] = 833,
  [SMALL_STATE(42)] = 846,
  [SMALL_STATE(43)] = 859,
  [SMALL_STATE(44)] = 867,
  [SMALL_STATE(45)] = 875,
  [SMALL_STATE(46)] = 883,
  [SMALL_STATE(47)] = 890,
  [SMALL_STATE(48)] = 897,
  [SMALL_STATE(49)] = 904,
  [SMALL_STATE(50)] = 911,
  [SMALL_STATE(51)] = 918,
  [SMALL_STATE(52)] = 925,
  [SMALL_STATE(53)] = 932,
  [SMALL_STATE(54)] = 939,
  [SMALL_STATE(55)] = 946,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_char, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_template_expr, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line_group, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line_group, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stmt, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_line, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_statement, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_statement, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dir_statement, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dir_statement, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_line_group_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stmt, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_member_access_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [197] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_betwork(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "betwork",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
